- hosts: all
  tasks:

    - name: check command_1 stdout
      ansible.builtin.shell: echo "checking output2..."
      failed_when: output1 == "{{ command_1_failed_condition }}"
    
    - name: check command_2 stdout
      ansible.builtin.shell: echo "checking output2..."
      failed_when: output2 == "{{ command_2_failed_condition }}"